vich_uploader:
  db_driver: orm

  mappings:
    avatar_file:
      uri_prefix: /uploads/userfile
      upload_destination: '%kernel.project_dir%/public/uploads/posters'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
